#!/usr/bin/env bash
# tests/e2e/ONT-059-recorded-exclusions.sh
#
# Recorded-exclusion e2e (ticket section 5): builds the workspace, then hands off
# to the sibling driver (ONT-059-recorded-exclusions.scenario.mjs), which drives
# the SHIPPED CLI over the ont-059 Prisma fixture through:
#   1. init --exclude ApiCredential -> no file and no action for it, the refusal
#      recorded in orangerail.governance.json, and the very next `sync` QUIET and
#      exit 0. That exit code is the defect: a narrowed project could never be
#      green, and the only remedy the report named (--accept-new) would have
#      generated the table that was deliberately kept off the agent's surface.
#   2. a model added AFTER the refusal is still a loud proposal with exit 1 while
#      the refused one stays quiet; --accept-new creates the new one and still not
#      the refused one; a recorded name that matches nothing is reported as
#      prunable rather than left to silence a future table of that name.
#   3. the refusals: an unknown --exclude name, a name in both --models and
#      --exclude, an --exclude covering everything, `sync --exclude` with no
#      baseline, and `sync --exclude` on a model the ontology already exposes.
#      None of them writes anything.
#
# No database is needed — every claim is read off generated bytes, the recorded
# baseline, and CLI exit codes.
#
# RED (pre-implementation): `--exclude` is not a flag, so phase 1's init exits
# non-zero on an unknown flag; without the flag, the follow-up `sync` proposes
# ApiCredential and exits 1.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

RED='\033[0;31m'
GREEN='\033[0;32m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${BOLD}── ONT-059 recorded exclusions e2e ──${NC}"

# The scenario drives the SHIPPED artifacts (dist bins), not source imports.
if ! pnpm -r run build > /dev/null 2>&1; then
  echo -e "${BOLD}${RED}workspace build failed${NC}"
  echo -e "${BOLD}${RED}========== ONT-059 E2E FAIL ==========${NC}"
  exit 1
fi

if node tests/e2e/ONT-059-recorded-exclusions.scenario.mjs; then
  echo -e "${BOLD}${GREEN}========== ONT-059 E2E PASS ==========${NC}"
  exit 0
fi

echo -e "${BOLD}${RED}========== ONT-059 E2E FAIL ==========${NC}"
exit 1
