#!/usr/bin/env bash
# tests/e2e/ONT-063-model-name-casing.sh
#
# Model-name casing e2e (ticket section 5): builds the workspace, then hands off
# to the sibling driver (ONT-063-model-name-casing.scenario.mjs), which drives
# the SHIPPED CLI over the ont-063 Prisma fixture through:
#   1. init --exclude payment on a schema declaring Payment -> the run succeeds,
#      generates nothing for the table, and records the SCANNED name in
#      orangerail.governance.json; the next `orangerail sync` is green and names
#      Payment. That last step is the assertion that matters: a lenient
#      comparison recording the typed string would pass every unit test and leave
#      a committed deny-list that `excluded.has(name)` never matches -- the
#      ONT-059 defect back again behind a file that looks right.
#   2. --models in the typed casing generates byte-identical output to --models
#      in the scanned casing.
#   3. the refusals that survive: a name matching nothing even ignoring case, a
#      plural and a prefix (no fuzzy rule rescues them), the same model in both
#      flags in different casings, and a schema whose model names differ only in
#      case -- refused, not picked between. None of them writes a config.
#   4. the same resolution on `orangerail sync --exclude`, the command whose own
#      report tells an operator to type a model name.
#
# No database is needed -- every claim is read off generated bytes, the recorded
# baseline, and CLI exit codes.
#
# RED (pre-implementation): phase 1 fails immediately -- `init --exclude payment`
# exits 1 with `unknown model "payment" in --exclude`.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

RED='\033[0;31m'
GREEN='\033[0;32m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${BOLD}── ONT-063 model name casing e2e ──${NC}"

# The scenario drives the SHIPPED artifacts (dist bins), not source imports.
if ! pnpm -r run build > /dev/null 2>&1; then
  echo -e "${BOLD}${RED}workspace build failed${NC}"
  echo -e "${BOLD}${RED}========== ONT-063 E2E FAIL ==========${NC}"
  exit 1
fi

if node tests/e2e/ONT-063-model-name-casing.scenario.mjs; then
  echo -e "${BOLD}${GREEN}========== ONT-063 E2E PASS ==========${NC}"
  exit 0
fi

echo -e "${BOLD}${RED}========== ONT-063 E2E FAIL ==========${NC}"
exit 1
