/**
 * Orangerail config (generated by `orangerail init`).
 *
 * This file is yours — re-scans never modify it; `orangerail sync` reports drift.
 * It self-discovers the ontology: every `ontology/*.mjs` is imported (which
 * registers it) before the shared registry and a file store are exported. A
 * new file dropped into `ontology/` registers automatically — no edit here.
 */
import { readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { createFileStore } from 'orangerail-core';

import { registry } from './ontology/_registry.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const ontologyDir = join(here, 'ontology');

const files = readdirSync(ontologyDir)
  .filter((name) => name.endsWith('.mjs') && name !== '_registry.mjs')
  .sort();

for (const name of files) {
  await import(pathToFileURL(join(ontologyDir, name)).href);
}

// The store below is INSIDE this project. An agent holding file tools over
// this directory can therefore write it, and one appended line in
// `.orangerail/store/approvals.jsonl` is a decision no human made: the
// next `check_approval` executes the staged action, because the gate reads
// this store and never the audit chain. `orangerail audit verify` reports the
// forgery afterwards — it is a report, not a gate, and it cannot un-execute a
// write. To take the store out of the agent's reach, point `dir` at a
// directory the agent's process cannot write — the commented line below — and
// leave exactly one of the two live. See docs/audit-log.md.
const store = createFileStore({ dir: join(here, '.orangerail', 'store') });
// const store = createFileStore({ dir: '/var/lib/orangerail/store' });

export default {
  registry,
  store,
  preset: "approval-for-writes",
  // Local-operator dev mode: with no `resolveIdentity` adapter the MCP
  // server denies every caller by default (secure by default). This scaffold
  // is a local single-user project, so it opts in to the all-roles
  // `local-dev` identity to make the flow work out of the box. Before
  // exposing this server to anyone else, add a `resolveIdentity` adapter (it
  // takes precedence and this flag is ignored) and remove this line.
  allowDevMode: true,
};
