/**
 * orangerail-docs-gen — the prompt rail (DESIGN.md §2).
 *
 * Walks an ontology registry and deterministically generates the agent-facing
 * domain document (AGENTS.md sections + an embedded Mermaid `classDiagram`)
 * that describes the runtime rail truthfully. Two pure functions, zero I/O —
 * file writing lives only in the `orangerail docs` CLI command (AC-1). Runtime
 * dependency is `orangerail-core` alone (AC-9); `mermaid`/`jsdom` are dev-only
 * (parse-backed validity tests). Output is byte-deterministic: entities sorted
 * alphabetically, no timestamps or randomness (AC-6).
 */
import type { Registry } from 'orangerail-core';

import { generateMermaid } from './mermaid';
import {
  renderActionTypes,
  renderAgentGuide,
  renderLinkTypes,
  renderMcpTools,
  renderObjectTypes,
  type DocsPreset,
} from './sections';

export { generateMermaid } from './mermaid';
export { deriveTools } from './sections';
export type { DocsPreset, DerivedTool } from './sections';

const HEADER = '<!-- Generated by `orangerail docs`. DO NOT EDIT — regenerate instead. -->';

/**
 * Generate the complete agent-facing domain document from a registry (AC-1).
 * `preset` mirrors the MCP server's exposure (defaulting to
 * `'approval-for-writes'` exactly like `createMcpServer`): it selects which
 * tools the document claims and which agent-usage guide it renders, so the two
 * rails never disagree (§3.1).
 */
export const generateDocs = ({
  registry,
  preset = 'approval-for-writes',
}: {
  registry: Registry;
  preset?: DocsPreset;
}): string => {
  const sections = [
    HEADER,
    '# Domain ontology',
    renderAgentGuide({ registry, preset }),
    ['## Domain map', '', '```mermaid', generateMermaid({ registry }), '```'].join('\n'),
    renderMcpTools({ registry, preset }),
    renderObjectTypes({ registry }),
    renderLinkTypes({ registry }),
    renderActionTypes({ registry, preset }),
  ];

  return `${sections.join('\n\n')}\n`;
};
