/**
 * Shared ontology registry (generated by `orangerail init`).
 *
 * This file is yours — re-scans never modify it; `orangerail sync` reports drift.
 * Every generated ontology file registers into this one instance; the config
 * imports it after loading them all.
 */
import { createRegistry } from 'orangerail-core';

export const registry = createRegistry();
