import type { McpPreset } from 'orangerail-mcp';

import { ownershipLine } from './emit-object';
import { escapeStringLiteral } from './escape';

/**
 * Emit the shared registry module and the self-discovering config (plan D5).
 * `_registry.mjs` exports one `createRegistry()` instance that every generated
 * ontology file registers into; `orangerail.config.mjs` imports it, dynamic
 * imports every other `ontology/*.mjs` (which triggers registration), then
 * exports `{ registry, store, preset }`. A sync-proposed new file registers
 * with zero edits to any existing file (§5.1.5) and no CLI-side glob feature is
 * needed. The file store lives under `.orangerail/store` — NOT under
 * `.orangerail/generated` (which is byte-compared and docs-owned).
 */

/** `_registry.mjs` — the shared registry instance (static, deterministic). */
export const emitRegistryFile = (): { filename: string; content: string } => {
  const content = [
    '/**',
    ' * Shared ontology registry (generated by `orangerail init`).',
    ' *',
    ` * ${ownershipLine}`,
    ' * Every generated ontology file registers into this one instance; the config',
    ' * imports it after loading them all.',
    ' */',
    "import { createRegistry } from 'orangerail-core';",
    '',
    'export const registry = createRegistry();',
    '',
  ].join('\n');

  return { filename: '_registry.mjs', content };
};

/** `orangerail.config.mjs` — the self-discovering entry point (static, deterministic). */
export const emitConfigFile = ({
  preset,
}: {
  preset: McpPreset;
}): { filename: string; content: string } => {
  const content = [
    '/**',
    ' * Orangerail config (generated by `orangerail init`).',
    ' *',
    ` * ${ownershipLine}`,
    ' * It self-discovers the ontology: every `ontology/*.mjs` is imported (which',
    ' * registers it) before the shared registry and a file store are exported. A',
    ' * new file dropped into `ontology/` registers automatically — no edit here.',
    ' */',
    "import { readdirSync } from 'node:fs';",
    "import { dirname, join } from 'node:path';",
    "import { fileURLToPath, pathToFileURL } from 'node:url';",
    '',
    "import { createFileStore } from 'orangerail-core';",
    '',
    "import { registry } from './ontology/_registry.mjs';",
    '',
    'const here = dirname(fileURLToPath(import.meta.url));',
    "const ontologyDir = join(here, 'ontology');",
    '',
    'const files = readdirSync(ontologyDir)',
    "  .filter((name) => name.endsWith('.mjs') && name !== '_registry.mjs')",
    '  .sort();',
    '',
    'for (const name of files) {',
    '  await import(pathToFileURL(join(ontologyDir, name)).href);',
    '}',
    '',
    "const store = createFileStore({ dir: join(here, '.orangerail', 'store') });",
    '',
    'export default {',
    '  registry,',
    '  store,',
    `  preset: ${escapeStringLiteral({ value: preset })},`,
    '  // Local-operator dev mode: with no `resolveIdentity` adapter the MCP',
    '  // server denies every caller by default (secure by default). This scaffold',
    '  // is a local single-user project, so it opts in to the all-roles',
    '  // `local-dev` identity to make the flow work out of the box. Before',
    '  // exposing this server to anyone else, add a `resolveIdentity` adapter (it',
    '  // takes precedence and this flag is ignored) and remove this line.',
    '  allowDevMode: true,',
    '};',
    '',
  ].join('\n');

  return { filename: 'orangerail.config.mjs', content };
};
