import { DECIMAL_INTEGER_SOURCE } from 'orangerail-core';
import { z } from 'zod';

import type { IrActionField, IrField, IrScalar, IrValueConstraints } from '../ir';
import { escapeStringLiteral } from './escape';

/**
 * The decimal-string form a `BigInt` column is carried in (ONT-068), as an
 * expression and as the matching node — one pattern, taken from core, rendered
 * into generated code through the same escaping layer a user's own `regex`
 * constraint goes through (D10).
 *
 * `z.bigint()` was the previous mapping and it made the column UNCALLABLE:
 * `JSON.parse` never yields a BigInt, so no JSON value satisfies it — `1`,
 * `"1"`, `null`, `[1]` and a raw wire literal were all refused with
 * `"id" expects bigint`. On an ordinary column that was a nuisance; on a primary
 * key it took `update` and `delete` off the surface entirely, and a `BigInt`
 * primary key is what both Laravel and Rails have generated by default for
 * years.
 *
 * The `.regex(...)` is not decoration. It is what refuses `"not-a-number"`,
 * `""`, `"1.5"` and `"0x10"` AT THE GATE, with a message naming the field —
 * rather than letting them reach a driver whose answer (`Cannot convert
 * not-a-number to a BigInt`) is redacted to an opaque `resolve_error`. It is
 * also what lets the transport tell this column apart from a `String` one, which
 * is what keeps `contains` off a filter Prisma's `BigIntFilter` cannot answer.
 */
const bigintExpr = `z.string().regex(new RegExp(${escapeStringLiteral({ value: DECIMAL_INTEGER_SOURCE })}))`;

/**
 * The single source of truth mapping an IR scalar to (a) the zod EXPRESSION the
 * emitter renders into generated code and (b) the actual zod NODE the sync
 * differ builds to compare against the live registry. Keeping both derived from
 * one table guarantees the emitted schema and the differ's expectation stay in
 * lockstep — a field is "drifted" iff the node the re-scan would generate
 * introspects differently from the registry's node (plan D6/D11).
 *
 * Distinct scalars intentionally render distinguishable nodes where drift must
 * be observable: `decimal` -> `z.string()` while `float` -> `z.number()`, so a
 * Prisma `Float -> Decimal` change surfaces as a type-name drift.
 *
 * `bigint` joins the string-shaped scalars ({@link bigintExpr}), so a Prisma
 * `BigInt -> Decimal` change no longer surfaces here — the differ compares the
 * introspected TYPE NAME, and both are `string`. That is the same imprecision
 * `decimal` and `datetime` have always had between them, and it is the price of
 * the only wire form a 64-bit key survives: the alternative was a node no JSON
 * value satisfies, which reports no drift either because the column is
 * unreachable.
 */
const SCALARS: Record<IrScalar, { expr: string; build: () => z.ZodType }> = {
  string: { expr: 'z.string()', build: () => z.string() },
  int: { expr: 'z.number().int()', build: () => z.number().int() },
  float: { expr: 'z.number()', build: () => z.number() },
  bigint: {
    expr: bigintExpr,
    build: () => z.string().regex(new RegExp(DECIMAL_INTEGER_SOURCE)),
  },
  decimal: { expr: 'z.string()', build: () => z.string() },
  boolean: { expr: 'z.boolean()', build: () => z.boolean() },
  datetime: { expr: 'z.string()', build: () => z.string() },
  json: { expr: 'z.unknown()', build: () => z.unknown() },
  bytes: { expr: 'z.string()', build: () => z.string() },
};

const enumExpr = ({ values }: { values: string[] }): string => {
  if (values.length === 0) {
    return 'z.string()';
  }

  return `z.enum([${values.map((v) => escapeStringLiteral({ value: v })).join(', ')}])`;
};

const enumNode = ({ values }: { values: string[] }): z.ZodType => {
  if (values.length === 0) {
    return z.string();
  }

  return z.enum(values as [string, ...string[]]);
};

/** The base (pre-modifier) expression + node for a scalar/enum field. */
const baseOf = ({
  field,
}: {
  field: IrField | IrActionField;
}): { expr: string; build: () => z.ZodType } => {
  if (field.kind === 'enum') {
    const values = field.enumValues ?? [];

    return { expr: enumExpr({ values }), build: () => enumNode({ values }) };
  }

  return SCALARS[field.scalar ?? 'string'];
};

/** The full zod expression string for a scanned object field (emitter side). */
export const fieldExpr = ({ field }: { field: IrField }): string => {
  const base = baseOf({ field });

  let expr = base.expr;

  if (field.list) {
    expr = `z.array(${expr})`;
  }

  if (field.optional) {
    expr = `${expr}.optional()`;
  }

  return expr;
};

/** Numeric-bound keys, in the order they are chained onto the base expression. */
const BOUND_METHODS = ['min', 'gt', 'max', 'lt'] as const;

/**
 * Render the declared value constraints (ONT-037) as a chain of zod modifiers.
 * The key names ARE the method names and the order is fixed, so the same IR
 * always emits the same bytes and a constraint-free field emits nothing at all.
 * A `regex` source goes through the one escaping layer (D10) and is rebuilt with
 * `new RegExp(...)` rather than a `/…/` literal, which no amount of user input
 * can terminate early.
 */
const constraintSuffix = ({
  constraints,
}: {
  constraints: IrValueConstraints | undefined;
}): string => {
  if (constraints === undefined) {
    return '';
  }

  const parts = BOUND_METHODS.filter((method) => constraints[method] !== undefined).map(
    (method) => `.${method}(${constraints[method] as number})`,
  );

  if (constraints.regex !== undefined) {
    parts.push(`.regex(new RegExp(${escapeStringLiteral({ value: constraints.regex })}))`);
  }

  return parts.join('');
};

/**
 * The base expression for an action input field, nested objects included
 * (ONT-042 A). An object renders its declared properties recursively so a
 * request body's nested shape survives into the emitted zod instead of
 * collapsing to `z.string()`; a shape the scanner could not express never
 * reaches here (it is reported and downgraded to `json` -> `z.unknown()`).
 * Keys go through the one escaping layer (D10), exactly like the top level.
 */
const actionBaseExpr = ({ field }: { field: IrActionField }): string => {
  if (field.kind !== 'object') {
    return baseOf({ field }).expr;
  }

  const entries = (field.fields ?? []).map(
    (child) =>
      `${escapeStringLiteral({ value: child.name })}: ${actionFieldExpr({ field: child })}`,
  );

  return entries.length === 0 ? 'z.object({})' : `z.object({ ${entries.join(', ')} })`;
};

/** The full zod expression string for a scanned action input field. */
export const actionFieldExpr = ({ field }: { field: IrActionField }): string => {
  // The constraints bind the ITEM of an array (`minLength` on `items`), so they
  // are chained before the `z.array(...)` wrapper, and `.optional()` stays
  // outermost: it says whether the caller has to supply the field at all.
  const constrained = `${actionBaseExpr({ field })}${constraintSuffix({ constraints: field.constraints })}`;
  const expr = field.list === true ? `z.array(${constrained})` : constrained;

  return field.optional ? `${expr}.optional()` : expr;
};

/** The actual zod node a scanned object field maps to (differ side). */
export const fieldNode = ({ field }: { field: IrField }): z.ZodType => {
  const base = baseOf({ field });

  let node = base.build();

  if (field.list) {
    node = z.array(node);
  }

  if (field.optional) {
    node = node.optional();
  }

  return node;
};
