import type { GeneratedFile } from '../codegen';
import { escapeStringLiteral, sanitizeMcpName } from '../codegen/escape';
import { renderReport } from './report';
import type { ExtractedOntology } from './types';

/**
 * Dedicated fixed-template emitter for the human-source ontology (plan Step 8).
 * Unlike the Prisma/OpenAPI codegen — whose `resolve` is a lazy-`@prisma/client`
 * stub — this emits an `orangerail.config.mjs` whose objects/links `resolve` by
 * reading committed `data/*.json` instance files. The type set is fixed
 * (employee/team/service/incident + member_of/works_on/helps, and a governed
 * deploy_service action where a gate is evidenced), so the config body is a
 * static template: all variable data lives in the JSON files, serialized with
 * `JSON.stringify` (its own escaping) and stable key order. Object/link/action
 * names still route through `sanitizeMcpName` so the reuse of the escape layer
 * is real and the emitted names are guaranteed-legal. Same input -> same bytes.
 */

/** Serialize a value as a committed data file (stable, newline-terminated). */
const dataFile = ({ name, value }: { name: string; value: unknown }): GeneratedFile => ({
  path: `data/${name}`,
  content: `${JSON.stringify(value, null, 2)}\n`,
});

const OBJECT_NAMES = {
  employee: sanitizeMcpName({ value: 'employee' }),
  team: sanitizeMcpName({ value: 'team' }),
  service: sanitizeMcpName({ value: 'service' }),
  incident: sanitizeMcpName({ value: 'incident' }),
};

const LINK_NAMES = {
  memberOf: sanitizeMcpName({ value: 'member_of' }),
  worksOn: sanitizeMcpName({ value: 'works_on' }),
  helps: sanitizeMcpName({ value: 'helps' }),
};

/** Render the static config module body (data lives in the JSON files). */
const renderConfig = ({ deployGateEvidenced }: { deployGateEvidenced: boolean }): string => {
  const lines: string[] = [
    '/**',
    ' * Orangerail config (generated by `orangerail init --from-jira`).',
    ' *',
    ' * A human-source org ontology extracted deterministically from a Jira and',
    ' * (optionally) a Slack export. No model was called: every number in',
    ' * data/*.json is a structural proxy computed by field math — see ANALYTICS.md',
    ' * for the formula behind each. This file is a fixed template; all instance',
    ' * data is read from the committed data/*.json files on every resolve.',
    ' */',
    "import { readFileSync } from 'node:fs';",
    "import { dirname, join } from 'node:path';",
    "import { fileURLToPath } from 'node:url';",
    '',
    "import { createFileStore, createRegistry } from 'orangerail-core';",
    "import { z } from 'zod';",
    '',
    'const here = dirname(fileURLToPath(import.meta.url));',
    "const dataDir = join(here, 'data');",
    '',
    "const load = ({ file }) => JSON.parse(readFileSync(join(dataDir, file), 'utf8'));",
    '',
    'const registry = createRegistry();',
    '',
    'const metric = z.union([z.number(), z.literal("unavailable")]);',
    '',
    `const ${OBJECT_NAMES.employee} = registry.defineObject({`,
    `  name: ${escapeStringLiteral({ value: OBJECT_NAMES.employee })},`,
    '  schema: z',
    '    .object({',
    '      accountId: z.string(),',
    '      displayName: z.string(),',
    '      active: z.boolean(),',
    '      ticketCount: z.number(),',
    '      storyPointsTotal: z.number(),',
    '      complexityMix: z.object({ hi: z.number(), med: z.number(), lo: z.number() }),',
    '      medianCycleDaysFirstHalf: z.number(),',
    '      medianCycleDaysSecondHalf: z.number(),',
    '      reopenRate: metric,',
    '      reassignmentsGiven: metric,',
    '      reassignmentsReceived: metric,',
    '      helpGiven: z.number(),',
    '      helpReceived: z.number(),',
    '      weekendOffHoursShare: z.number(),',
    '    })',
    '    .passthrough(),',
    '  resolve: {',
    "    get: async ({ id }) => load({ file: 'employee.json' }).find((e) => e.accountId === id) ?? null,",
    "    list: async () => ({ items: load({ file: 'employee.json' }) }),",
    '  },',
    '});',
    '',
    `const ${OBJECT_NAMES.team} = registry.defineObject({`,
    `  name: ${escapeStringLiteral({ value: OBJECT_NAMES.team })},`,
    '  schema: z.object({ id: z.string(), name: z.string(), project: z.string() }),',
    '  resolve: {',
    "    get: async ({ id }) => load({ file: 'team.json' }).find((t) => t.id === id) ?? null,",
    "    list: async () => ({ items: load({ file: 'team.json' }) }),",
    '  },',
    '});',
    '',
    `const ${OBJECT_NAMES.service} = registry.defineObject({`,
    `  name: ${escapeStringLiteral({ value: OBJECT_NAMES.service })},`,
    '  schema: z',
    '    .object({',
    '      id: z.string(),',
    '      name: z.string(),',
    '      ticketCount: z.number(),',
    '      distinctAssignees: z.number(),',
    '      busFactor: z.number(),',
    '    })',
    '    .passthrough(),',
    '  resolve: {',
    "    get: async ({ id }) => load({ file: 'service.json' }).find((s) => s.id === id) ?? null,",
    "    list: async () => ({ items: load({ file: 'service.json' }) }),",
    '  },',
    '});',
    '',
    `const ${OBJECT_NAMES.incident} = registry.defineObject({`,
    `  name: ${escapeStringLiteral({ value: OBJECT_NAMES.incident })},`,
    '  schema: z',
    '    .object({',
    '      id: z.string(),',
    '      date: z.string(),',
    '      channel: z.string(),',
    '      threadTs: z.string(),',
    '      leadResponderAccountId: z.string(),',
    '      leadResponder: z.string(),',
    '      hasTrackerIssue: z.boolean(),',
    '    })',
    '    .passthrough(),',
    '  resolve: {',
    "    get: async ({ id }) => load({ file: 'incident.json' }).find((i) => i.id === id) ?? null,",
    "    list: async () => ({ items: load({ file: 'incident.json' }) }),",
    '  },',
    '});',
    '',
    `registry.defineLink({ name: ${escapeStringLiteral({ value: LINK_NAMES.memberOf })}, from: ${OBJECT_NAMES.employee}, to: ${OBJECT_NAMES.team}, cardinality: 'one' });`,
    `registry.defineLink({ name: ${escapeStringLiteral({ value: LINK_NAMES.worksOn })}, from: ${OBJECT_NAMES.employee}, to: ${OBJECT_NAMES.service}, cardinality: 'many' });`,
    `registry.defineLink({ name: ${escapeStringLiteral({ value: LINK_NAMES.helps })}, from: ${OBJECT_NAMES.employee}, to: ${OBJECT_NAMES.employee}, cardinality: 'many' });`,
    '',
  ];

  if (deployGateEvidenced) {
    lines.push(
      '/**',
      ' * A production deploy is a GOVERNED action with approval REQUIRED — a deploy',
      ' * gate is evidenced in the chat export. The action stages and waits for a',
      ' * human; a wrong guess in this generated ontology cannot execute anything.',
      ' */',
      'registry.defineAction({',
      `  name: ${escapeStringLiteral({ value: sanitizeMcpName({ value: 'deploy_service' }) })},`,
      `  target: ${OBJECT_NAMES.service},`,
      '  input: z.object({ serviceId: z.string(), note: z.string() }),',
      "  policy: { approval: 'required' },",
      '  execute: async ({ input }) => ({ deployed: input.serviceId }),',
      '});',
      '',
    );
  }

  lines.push(
    "const store = createFileStore({ dir: join(here, '.orangerail', 'store') });",
    '',
    'export default {',
    '  registry,',
    '  store,',
    '};',
    '',
  );

  return lines.join('\n');
};

/**
 * Emit the full byte-deterministic file set: the config module, one JSON file
 * per object/link instance array, the layer-2 candidate evidence, the findings,
 * and the human-facing ANALYTICS.md report.
 */
export const emitArtifacts = ({ ontology }: { ontology: ExtractedOntology }): GeneratedFile[] => {
  const files: GeneratedFile[] = [];

  files.push({
    path: 'orangerail.config.mjs',
    content: renderConfig({ deployGateEvidenced: ontology.deployGateEvidenced }),
  });

  files.push(dataFile({ name: 'employee.json', value: ontology.employees }));
  files.push(dataFile({ name: 'team.json', value: [ontology.team] }));
  files.push(dataFile({ name: 'service.json', value: ontology.services }));
  files.push(dataFile({ name: 'incident.json', value: ontology.incidents }));
  files.push(dataFile({ name: 'member_of.json', value: ontology.memberOf }));
  files.push(dataFile({ name: 'works_on.json', value: ontology.worksOn }));
  files.push(dataFile({ name: 'helps.json', value: ontology.helps }));
  files.push(dataFile({ name: 'candidate.json', value: ontology.candidates }));
  files.push(dataFile({ name: 'finding.json', value: ontology.findings }));

  files.push({ path: 'ANALYTICS.md', content: renderReport({ ontology }) });

  return files;
};
